# Generated by Django 6.0.3 on 2026-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Cinematic Film", "Cinematic Film"),
                            ("Viral Reel", "Viral Reel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="films/thumbnails/")),
                (
                    "video_id",
                    models.CharField(
                        help_text="YouTube Video ID (e.g., dQw4w9WgXcQ from youtube.com/watch?v=dQw4w9WgXcQ)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="gallery/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Pre-Wedding", "Pre-Wedding"),
                            ("Wedding", "Wedding"),
                            ("Maternity", "Maternity"),
                            ("Newborn", "Newborn"),
                            ("Toddler", "Toddler"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("Wedding Photography", "Wedding Photography"),
                            ("Pre-Wedding Shoot", "Pre-Wedding Shoot"),
                            ("Films & Cinematography", "Films & Cinematography"),
                            ("Commercial/Event", "Commercial/Event"),
                        ],
                        max_length=100,
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "vision",
                    models.TextField(
                        help_text="Client's message / description of their vision"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("text", models.TextField()),
                (
                    "client_image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("is_featured", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
