# Generated by Django 6.0.3 on 2026-04-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="video_id",
            field=models.CharField(
                help_text="YouTube Video ID (e.g., dQw4w9WgXcQ from youtube.com/watch?v=dQw4w9WgXcQ)",
                max_length=200,
            ),
        ),
    ]
