# Generated by Django 6.0.3 on 2026-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_film_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
