# Generated by Django 6.0.3 on 2026-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_alter_film_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="film",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="film",
            name="thumbnail",
        ),
        migrations.AlterField(
            model_name="film",
            name="video_id",
            field=models.CharField(
                help_text="YouTube Video ID or Full URL", max_length=200
            ),
        ),
    ]
