# Generated by Django 6.0.3 on 2026-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_alter_film_options_remove_film_thumbnail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquiry",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="inquiry",
            name="vision",
        ),
        migrations.AddField(
            model_name="inquiry",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
