# Generated by Django 6.0.3 on 2026-04-07 07:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_remove_inquiry_event_date_remove_inquiry_vision_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={"ordering": ["-is_featured", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="client_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
