# Generated by Django 6.0.3 on 2026-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gallery",
            "0006_alter_galleryitem_options_alter_testimonial_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="video_id",
            field=models.CharField(
                help_text="Enter YouTube Video ID or the full YouTube URL",
                max_length=200,
            ),
        ),
    ]
