# Generated by Django 6.0.3 on 2026-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_film_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Pre-Wedding", "Pre-Wedding"),
                    ("Wedding", "Wedding"),
                    ("Maternity", "Maternity"),
                    ("Newborn", "Newborn"),
                    ("Toddler", "Toddler"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
