# Generated by Django 6.0.3 on 2026-04-20 04:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0008_alter_galleryitem_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Pre-Wedding", "Pre-Wedding"),
                            ("Wedding", "Wedding"),
                            ("Portrait", "Portrait"),
                            ("Event", "Event"),
                        ],
                        default="Wedding",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(help_text="A short summary of the blog post"),
                ),
                ("content", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
