# Generated by Django 6.0.3 on 2026-04-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0010_alter_blog_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("feedback_text", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
